name: 05 - Event Filters
on: 
    push:
        branches:
            - 'features/*'

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: echo "Running whenever branch is features"
