name: 05 - Event Filters
on: 
    push:
        branches:
            - 'feature/*'

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo "Hello, World!"
